extends: default

ignore: |
  config/home-assistant/configuration.yaml

rules:
  line-length: disable
  document-start: disable
  truthy: disable
  comments-indentation: disable
  indentation:
    indent-sequences: consistent
