version: 3

dotenv:
  - .env

tasks:
  install:
    cmds:
      - chmod +x docker.sh
      - chmod +x tailscale.sh
      - sh docker.sh
      - docker network create dockarr
      - sh joal-setup.sh
    dir: install
  pihole-up:
    cmds:
      - docker compose up -d
    dir: pihole
  transmission-up:
    cmd: docker compose up -d
    dir: transmission
  joal-up:
    cmd: docker compose up -d
    dir: joal
  stirling-up:
    cmd: docker compose up -d
    dir: stirling
  servarr-up:
    cmd: docker compose up -d
    dir: servarr
  vaultwarden-up:
    cmd: docker compose up -d
    dir: vaultwarden
  jellyfin-up:
    cmd: docker compose up -d
    dir: jellyfin
  jellyseerr-up:
    cmd: docker compose up -d
    dir: jellyseerr
  home-assistant-up:
    cmd: docker compose up -d
    dir: home-assistant
  portainer-up:
    cmd: docker compose up -d
    dir: portainer
  homepage-up:
    cmd: docker compose up -d
    dir: homepage
  start:
    cmds:
      - task pihole-up
      - task transmission-up
      - task joal-up
      - task stirling-up
      - task servarr-up
      - task vaultwarden-up
      - task jellyfin-up
      - task jellyseerr-up
      - task home-assistant-up
      - task portainer-up
      - task homepage-up
  pihole-down:
    cmd: docker compose down
    dir: pihole
  transmission-down:
    cmd: docker compose down
    dir: transmission
  joal-down:
    cmd: docker compose down
    dir: joal
  stirling-down:
    cmd: docker compose down
    dir: stirling
  servarr-down:
    cmd: docker compose down
    dir: servarr
  vaultwarden-down:
    cmd: docker compose down
    dir: vaultwarden
  jellyfin-down:
    cmd: docker compose down
    dir: jellyfin
  jellyseerr-down:
    cmd: docker compose down
    dir: jellyseerr
  home-assistant-down:
    cmd: docker compose down
    dir: home-assistant
  portainer-down:
    cmd: docker compose down
    dir: portainer
  homepage-down:
    cmd: docker compose down
    dir: homepage
  teardown:
    cmds:
      - docker stop $(docker ps -aq)
      - docker rm $(docker ps -aq)