services:
  gluetunp:
    image: qmcgaw/gluetun
    container_name: gluetunp
    ports:
      - "9696:9696"
    environment:
      - VPN_SERVICE_PROVIDER=${GLUETUN_PROVIDER}
      - VPN_TYPE=${GLUETUN_TYPE}
      - OPENVPN_USER=${GLUETUN_USER}
      - OPENVPN_PASSWORD=${GLUETUN_PASSWORD}
      - TZ=Europe/Amsterdam
      - SERVER_COUNTRIES=${GLUETUN_COUNTRIES}
    volumes:
      - ${CONFIG}/gluetunp:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    restart: always
  prowlarrvpn:
    image: linuxserver/prowlarr:2.3.5
    container_name: prowlarrvpn
    network_mode: service:gluetun
    volumes:
      - ${CONFIG}/prowlarrvpn:/config
    restart: always
    depends_on:
      - gluetunp